#微信支付配置信息
wechat:
  gzh: #公众号
    app-id: wx8094961ece166419   #sandbox
    secret: 16c794c6f95e347ca1b849abd84629c1   #sandbox
    welcome-content: 欢迎使用鲁颁建筑资质服务平台，您已登陆成功！   #sandbox
    bind-content: 微信绑定成功,当前账号为%s   #sandbox
    register-content: 扫码成功，请继续使用手机号完成注册！   #sandbox
    account: gh_fd17266ee510   #sandbox